"""Initial tenant-isolated ERP schema and restricted analytics access.

Revision ID: 0001_erp_foundation
Revises: None

Prerequisite: run the database bootstrap to create schemas owned by nlq_migrator
and the nlq_reader/nlq_app roles. This migration never creates or drops login roles.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001_erp_foundation"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

# Frozen lists belong to this revision. Do not import live application metadata here.
ERP_TABLES = (
    "customers",
    "suppliers",
    "product_categories",
    "products",
    "purchase_orders",
    "purchase_order_items",
    "sales_orders",
    "sales_order_items",
    "purchase_invoices",
    "sales_invoices",
    "payments",
    "stock",
)


def _install_database_policy() -> None:
    op.execute("""
        CREATE FUNCTION erp.authorized_tenant_id() RETURNS uuid
        LANGUAGE sql STABLE SECURITY DEFINER
        SET search_path = pg_catalog
        AS $$
            SELECT tenant_id FROM app.analytics_principals
            WHERE db_role = session_user::text
        $$
    """)
    op.execute("REVOKE ALL ON FUNCTION erp.authorized_tenant_id() FROM PUBLIC")
    op.execute("GRANT EXECUTE ON FUNCTION erp.authorized_tenant_id() TO nlq_reader")
    op.execute("""
        CREATE FUNCTION erp.touch_updated_at() RETURNS trigger
        LANGUAGE plpgsql
        SET search_path = pg_catalog
        AS $$
        BEGIN
            NEW.updated_at := clock_timestamp();
            RETURN NEW;
        END;
        $$
    """)
    op.execute("REVOKE ALL ON FUNCTION erp.touch_updated_at() FROM PUBLIC")
    op.execute("REVOKE ALL ON ALL TABLES IN SCHEMA erp FROM PUBLIC, nlq_app, nlq_reader")
    op.execute("REVOKE ALL ON ALL TABLES IN SCHEMA app FROM PUBLIC, nlq_reader, nlq_app")
    op.execute("GRANT USAGE ON SCHEMA erp TO nlq_reader")
    op.execute("GRANT USAGE ON SCHEMA app TO nlq_app")
    op.execute("GRANT SELECT ON app.tenants TO nlq_app")
    for table in ERP_TABLES:
        # Identifiers are fixed in this immutable migration, never user supplied.
        op.execute(f"ALTER TABLE erp.{table} ENABLE ROW LEVEL SECURITY")
        op.execute(
            f"CREATE POLICY tenant_reader ON erp.{table} FOR SELECT TO nlq_reader "
            "USING (tenant_id = (SELECT erp.authorized_tenant_id()))"
        )
        op.execute(f"GRANT SELECT ON erp.{table} TO nlq_reader")
    for table in ("app.tenants", *(f"erp.{name}" for name in ERP_TABLES)):
        op.execute(
            f"CREATE TRIGGER touch_updated_at BEFORE UPDATE ON {table} "
            "FOR EACH ROW EXECUTE FUNCTION erp.touch_updated_at()"
        )


def _remove_database_policy() -> None:
    for table in ("app.tenants", *(f"erp.{name}" for name in ERP_TABLES)):
        op.execute(f"DROP TRIGGER touch_updated_at ON {table}")
    for table in ERP_TABLES:
        op.execute(f"DROP POLICY tenant_reader ON erp.{table}")
        op.execute(f"REVOKE SELECT ON erp.{table} FROM nlq_reader")
    op.execute("REVOKE SELECT ON app.tenants FROM nlq_app")
    op.execute("REVOKE USAGE ON SCHEMA erp FROM nlq_reader")
    op.execute("DROP FUNCTION erp.authorized_tenant_id()")
    op.execute("DROP FUNCTION erp.touch_updated_at()")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tenants",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tenants")),
        sa.UniqueConstraint("slug", name=op.f("uq_tenants_slug")),
        schema="app",
        comment="Organizations that own isolated ERP data.",
    )
    op.create_table(
        "analytics_principals",
        sa.Column("db_role", sa.String(length=63), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["app.tenants.id"],
            name=op.f("fk_analytics_principals_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("db_role", name=op.f("pk_analytics_principals")),
        schema="app",
        comment="Trusted mapping from a database login to its authorized ERP tenant.",
    )
    op.create_index(
        op.f("ix_analytics_principals_tenant_id"),
        "analytics_principals",
        ["tenant_id"],
        unique=False,
        schema="app",
    )
    op.create_table(
        "seed_runs",
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["app.tenants.id"],
            name=op.f("fk_seed_runs_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("tenant_id", "version", name=op.f("pk_seed_runs")),
        schema="app",
        comment="Atomic, versioned demo seed completion records.",
    )
    op.create_table(
        "customers",
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=100), nullable=False),
        sa.Column("country", sa.String(length=100), server_default="India", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "tenant_id",
            sa.Uuid(),
            nullable=False,
            comment="Organization owning this record; enforced by foreign keys and reader RLS.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["app.tenants.id"],
            name=op.f("fk_customers_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint("tenant_id", "code", name="uq_customers_tenant_code"),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_customers_tenant_id")),
        schema="erp",
        comment="Customers placing sales orders.",
    )
    op.create_index(
        "ix_customers_tenant_name", "customers", ["tenant_id", "name"], unique=False, schema="erp"
    )
    op.create_table(
        "product_categories",
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "tenant_id",
            sa.Uuid(),
            nullable=False,
            comment="Organization owning this record; enforced by foreign keys and reader RLS.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["app.tenants.id"],
            name=op.f("fk_product_categories_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_categories")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_product_categories_tenant_id")),
        sa.UniqueConstraint("tenant_id", "name", name="uq_product_categories_tenant_name"),
        schema="erp",
        comment="Product categories used for inventory and sales grouping.",
    )
    op.create_table(
        "suppliers",
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=254), nullable=True),
        sa.Column("phone", sa.String(length=32), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=100), nullable=False),
        sa.Column("country", sa.String(length=100), server_default="India", nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "tenant_id",
            sa.Uuid(),
            nullable=False,
            comment="Organization owning this record; enforced by foreign keys and reader RLS.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["app.tenants.id"],
            name=op.f("fk_suppliers_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suppliers")),
        sa.UniqueConstraint("tenant_id", "code", name="uq_suppliers_tenant_code"),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_suppliers_tenant_id")),
        schema="erp",
        comment="Suppliers fulfilling purchase orders.",
    )
    op.create_index(
        "ix_suppliers_tenant_name", "suppliers", ["tenant_id", "name"], unique=False, schema="erp"
    )
    op.create_table(
        "products",
        sa.Column("sku", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.Column("unit", sa.String(length=20), server_default="unit", nullable=False),
        sa.Column("cost_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("selling_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column(
            "reorder_level", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "tenant_id",
            sa.Uuid(),
            nullable=False,
            comment="Organization owning this record; enforced by foreign keys and reader RLS.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cost_price >= 0 AND selling_price >= 0", name=op.f("ck_products_nonnegative_prices")
        ),
        sa.CheckConstraint(
            "reorder_level >= 0", name=op.f("ck_products_nonnegative_reorder_level")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "category_id"],
            ["erp.product_categories.tenant_id", "erp.product_categories.id"],
            name=op.f("fk_products_tenant_id_product_categories"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["app.tenants.id"],
            name=op.f("fk_products_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_products_tenant_id")),
        sa.UniqueConstraint("tenant_id", "sku", name="uq_products_tenant_sku"),
        schema="erp",
        comment="Catalog products; prices are denominated in INR.",
    )
    op.create_index(
        "ix_products_tenant_category",
        "products",
        ["tenant_id", "category_id"],
        unique=False,
        schema="erp",
    )
    op.create_index(
        "ix_products_tenant_name", "products", ["tenant_id", "name"], unique=False, schema="erp"
    )
    op.create_table(
        "purchase_orders",
        sa.Column("order_number", sa.String(length=50), nullable=False),
        sa.Column("supplier_id", sa.Uuid(), nullable=False),
        sa.Column("order_date", sa.Date(), nullable=False),
        sa.Column("expected_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=24), server_default="draft", nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="INR", nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "tenant_id",
            sa.Uuid(),
            nullable=False,
            comment="Organization owning this record; enforced by foreign keys and reader RLS.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("currency = 'INR'", name=op.f("ck_purchase_orders_currency")),
        sa.CheckConstraint(
            "status IN ('draft', 'confirmed', 'received', 'cancelled')",
            name=op.f("ck_purchase_orders_status"),
        ),
        sa.CheckConstraint(
            "expected_date IS NULL OR expected_date >= order_date",
            name=op.f("ck_purchase_orders_dates"),
        ),
        sa.CheckConstraint(
            "subtotal >= 0 AND tax_amount >= 0", name=op.f("ck_purchase_orders_nonnegative_amounts")
        ),
        sa.CheckConstraint(
            "total_amount = subtotal + tax_amount", name=op.f("ck_purchase_orders_total_amount")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "supplier_id"],
            ["erp.suppliers.tenant_id", "erp.suppliers.id"],
            name=op.f("fk_purchase_orders_tenant_id_suppliers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["app.tenants.id"],
            name=op.f("fk_purchase_orders_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_orders")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_purchase_orders_tenant_id")),
        sa.UniqueConstraint("tenant_id", "order_number", name="uq_purchase_orders_tenant_number"),
        schema="erp",
        comment="Purchases from suppliers; confirmed orders await receipt.",
    )
    op.create_index(
        "ix_purchase_orders_tenant_date",
        "purchase_orders",
        ["tenant_id", "order_date"],
        unique=False,
        schema="erp",
    )
    op.create_index(
        "ix_purchase_orders_tenant_status",
        "purchase_orders",
        ["tenant_id", "status"],
        unique=False,
        schema="erp",
    )
    op.create_index(
        "ix_purchase_orders_tenant_supplier",
        "purchase_orders",
        ["tenant_id", "supplier_id"],
        unique=False,
        schema="erp",
    )
    op.create_table(
        "sales_orders",
        sa.Column("order_number", sa.String(length=50), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("order_date", sa.Date(), nullable=False),
        sa.Column("delivery_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=24), server_default="draft", nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="INR", nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "tenant_id",
            sa.Uuid(),
            nullable=False,
            comment="Organization owning this record; enforced by foreign keys and reader RLS.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("currency = 'INR'", name=op.f("ck_sales_orders_currency")),
        sa.CheckConstraint(
            "status IN ('draft', 'confirmed', 'shipped', 'delivered', 'cancelled')",
            name=op.f("ck_sales_orders_status"),
        ),
        sa.CheckConstraint(
            "delivery_date IS NULL OR delivery_date >= order_date",
            name=op.f("ck_sales_orders_dates"),
        ),
        sa.CheckConstraint(
            "subtotal >= 0 AND tax_amount >= 0", name=op.f("ck_sales_orders_nonnegative_amounts")
        ),
        sa.CheckConstraint(
            "total_amount = subtotal + tax_amount", name=op.f("ck_sales_orders_total_amount")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "customer_id"],
            ["erp.customers.tenant_id", "erp.customers.id"],
            name=op.f("fk_sales_orders_tenant_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["app.tenants.id"],
            name=op.f("fk_sales_orders_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_orders")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_sales_orders_tenant_id")),
        sa.UniqueConstraint("tenant_id", "order_number", name="uq_sales_orders_tenant_number"),
        schema="erp",
        comment="Customer sales orders and their monetary totals.",
    )
    op.create_index(
        "ix_sales_orders_tenant_customer",
        "sales_orders",
        ["tenant_id", "customer_id"],
        unique=False,
        schema="erp",
    )
    op.create_index(
        "ix_sales_orders_tenant_date",
        "sales_orders",
        ["tenant_id", "order_date"],
        unique=False,
        schema="erp",
    )
    op.create_index(
        "ix_sales_orders_tenant_status",
        "sales_orders",
        ["tenant_id", "status"],
        unique=False,
        schema="erp",
    )
    op.create_table(
        "purchase_invoices",
        sa.Column("invoice_number", sa.String(length=50), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("invoice_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=24), server_default="draft", nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="INR", nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "tenant_id",
            sa.Uuid(),
            nullable=False,
            comment="Organization owning this record; enforced by foreign keys and reader RLS.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("currency = 'INR'", name=op.f("ck_purchase_invoices_currency")),
        sa.CheckConstraint(
            "status IN ('draft', 'issued', 'partially_paid', 'paid', 'overdue', 'cancelled')",
            name=op.f("ck_purchase_invoices_status"),
        ),
        sa.CheckConstraint("due_date >= invoice_date", name=op.f("ck_purchase_invoices_dates")),
        sa.CheckConstraint(
            "subtotal >= 0 AND tax_amount >= 0",
            name=op.f("ck_purchase_invoices_nonnegative_amounts"),
        ),
        sa.CheckConstraint(
            "total_amount = subtotal + tax_amount", name=op.f("ck_purchase_invoices_total_amount")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "order_id"],
            ["erp.purchase_orders.tenant_id", "erp.purchase_orders.id"],
            name=op.f("fk_purchase_invoices_tenant_id_purchase_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["app.tenants.id"],
            name=op.f("fk_purchase_invoices_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_invoices")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_purchase_invoices_tenant_id")),
        sa.UniqueConstraint(
            "tenant_id", "invoice_number", name="uq_purchase_invoices_tenant_number"
        ),
        schema="erp",
        comment="Supplier invoices; supplier is derived through purchase order.",
    )
    op.create_index(
        "ix_purchase_invoices_tenant_date",
        "purchase_invoices",
        ["tenant_id", "invoice_date"],
        unique=False,
        schema="erp",
    )
    op.create_index(
        "ix_purchase_invoices_tenant_due_status",
        "purchase_invoices",
        ["tenant_id", "due_date", "status"],
        unique=False,
        schema="erp",
    )
    op.create_index(
        "ix_purchase_invoices_tenant_order",
        "purchase_invoices",
        ["tenant_id", "order_id"],
        unique=False,
        schema="erp",
    )
    op.create_table(
        "purchase_order_items",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("tax_rate", sa.Numeric(precision=5, scale=2), server_default="0", nullable=False),
        sa.Column(
            "line_subtotal",
            sa.Numeric(precision=16, scale=2),
            sa.Computed("round(quantity * unit_price, 2)", persisted=True),
            nullable=False,
        ),
        sa.Column(
            "tax_amount",
            sa.Numeric(precision=16, scale=2),
            sa.Computed(
                "round(quantity * unit_price * tax_rate / 100::numeric, 2)", persisted=True
            ),
            nullable=False,
        ),
        sa.Column(
            "line_total",
            sa.Numeric(precision=16, scale=2),
            sa.Computed(
                "round(quantity * unit_price, 2) + "
                "round(quantity * unit_price * tax_rate / 100::numeric, 2)",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "tenant_id",
            sa.Uuid(),
            nullable=False,
            comment="Organization owning this record; enforced by foreign keys and reader RLS.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_purchase_order_items_positive_quantity")),
        sa.CheckConstraint(
            "tax_rate >= 0 AND tax_rate <= 100", name=op.f("ck_purchase_order_items_tax_rate")
        ),
        sa.CheckConstraint(
            "unit_price >= 0", name=op.f("ck_purchase_order_items_nonnegative_price")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "order_id"],
            ["erp.purchase_orders.tenant_id", "erp.purchase_orders.id"],
            name=op.f("fk_purchase_order_items_tenant_id_purchase_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "product_id"],
            ["erp.products.tenant_id", "erp.products.id"],
            name=op.f("fk_purchase_order_items_tenant_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["app.tenants.id"],
            name=op.f("fk_purchase_order_items_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_purchase_order_items")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_purchase_order_items_tenant_id")),
        schema="erp",
        comment="Purchase lines; monetary totals are generated by PostgreSQL.",
    )
    op.create_index(
        "ix_purchase_order_items_tenant_order",
        "purchase_order_items",
        ["tenant_id", "order_id"],
        unique=False,
        schema="erp",
    )
    op.create_index(
        "ix_purchase_order_items_tenant_product",
        "purchase_order_items",
        ["tenant_id", "product_id"],
        unique=False,
        schema="erp",
    )
    op.create_table(
        "sales_invoices",
        sa.Column("invoice_number", sa.String(length=50), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("invoice_date", sa.Date(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=24), server_default="draft", nullable=False),
        sa.Column("currency", sa.String(length=3), server_default="INR", nullable=False),
        sa.Column("subtotal", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("tax_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "tenant_id",
            sa.Uuid(),
            nullable=False,
            comment="Organization owning this record; enforced by foreign keys and reader RLS.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("currency = 'INR'", name=op.f("ck_sales_invoices_currency")),
        sa.CheckConstraint(
            "status IN ('draft', 'issued', 'partially_paid', 'paid', 'overdue', 'cancelled')",
            name=op.f("ck_sales_invoices_status"),
        ),
        sa.CheckConstraint("due_date >= invoice_date", name=op.f("ck_sales_invoices_dates")),
        sa.CheckConstraint(
            "subtotal >= 0 AND tax_amount >= 0", name=op.f("ck_sales_invoices_nonnegative_amounts")
        ),
        sa.CheckConstraint(
            "total_amount = subtotal + tax_amount", name=op.f("ck_sales_invoices_total_amount")
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "order_id"],
            ["erp.sales_orders.tenant_id", "erp.sales_orders.id"],
            name=op.f("fk_sales_invoices_tenant_id_sales_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["app.tenants.id"],
            name=op.f("fk_sales_invoices_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_invoices")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_sales_invoices_tenant_id")),
        sa.UniqueConstraint("tenant_id", "invoice_number", name="uq_sales_invoices_tenant_number"),
        schema="erp",
        comment="Customer invoices; customer is derived through sales order.",
    )
    op.create_index(
        "ix_sales_invoices_tenant_date",
        "sales_invoices",
        ["tenant_id", "invoice_date"],
        unique=False,
        schema="erp",
    )
    op.create_index(
        "ix_sales_invoices_tenant_due_status",
        "sales_invoices",
        ["tenant_id", "due_date", "status"],
        unique=False,
        schema="erp",
    )
    op.create_index(
        "ix_sales_invoices_tenant_order",
        "sales_invoices",
        ["tenant_id", "order_id"],
        unique=False,
        schema="erp",
    )
    op.create_table(
        "sales_order_items",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("tax_rate", sa.Numeric(precision=5, scale=2), server_default="0", nullable=False),
        sa.Column(
            "line_subtotal",
            sa.Numeric(precision=16, scale=2),
            sa.Computed("round(quantity * unit_price, 2)", persisted=True),
            nullable=False,
        ),
        sa.Column(
            "tax_amount",
            sa.Numeric(precision=16, scale=2),
            sa.Computed(
                "round(quantity * unit_price * tax_rate / 100::numeric, 2)", persisted=True
            ),
            nullable=False,
        ),
        sa.Column(
            "line_total",
            sa.Numeric(precision=16, scale=2),
            sa.Computed(
                "round(quantity * unit_price, 2) + "
                "round(quantity * unit_price * tax_rate / 100::numeric, 2)",
                persisted=True,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "tenant_id",
            sa.Uuid(),
            nullable=False,
            comment="Organization owning this record; enforced by foreign keys and reader RLS.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_sales_order_items_positive_quantity")),
        sa.CheckConstraint(
            "tax_rate >= 0 AND tax_rate <= 100", name=op.f("ck_sales_order_items_tax_rate")
        ),
        sa.CheckConstraint("unit_price >= 0", name=op.f("ck_sales_order_items_nonnegative_price")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "order_id"],
            ["erp.sales_orders.tenant_id", "erp.sales_orders.id"],
            name=op.f("fk_sales_order_items_tenant_id_sales_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "product_id"],
            ["erp.products.tenant_id", "erp.products.id"],
            name=op.f("fk_sales_order_items_tenant_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["app.tenants.id"],
            name=op.f("fk_sales_order_items_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_order_items")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_sales_order_items_tenant_id")),
        schema="erp",
        comment="Sales lines; monetary totals are generated by PostgreSQL.",
    )
    op.create_index(
        "ix_sales_order_items_tenant_order",
        "sales_order_items",
        ["tenant_id", "order_id"],
        unique=False,
        schema="erp",
    )
    op.create_index(
        "ix_sales_order_items_tenant_product",
        "sales_order_items",
        ["tenant_id", "product_id"],
        unique=False,
        schema="erp",
    )
    op.create_table(
        "stock",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("warehouse", sa.String(length=120), nullable=False),
        sa.Column(
            "quantity", sa.Numeric(precision=14, scale=2), server_default="0", nullable=False
        ),
        sa.Column(
            "reserved_quantity",
            sa.Numeric(precision=14, scale=2),
            server_default="0",
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "tenant_id",
            sa.Uuid(),
            nullable=False,
            comment="Organization owning this record; enforced by foreign keys and reader RLS.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "quantity >= 0 AND reserved_quantity >= 0 AND reserved_quantity <= quantity",
            name=op.f("ck_stock_valid_quantities"),
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "product_id"],
            ["erp.products.tenant_id", "erp.products.id"],
            name=op.f("fk_stock_tenant_id_products"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["app.tenants.id"],
            name=op.f("fk_stock_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_stock_tenant_id")),
        sa.UniqueConstraint(
            "tenant_id", "product_id", "warehouse", name="uq_stock_tenant_location"
        ),
        schema="erp",
        comment="Inventory snapshot by product and warehouse; available=quantity-reserved.",
    )
    op.create_table(
        "payments",
        sa.Column("payment_number", sa.String(length=50), nullable=False),
        sa.Column("purchase_invoice_id", sa.Uuid(), nullable=True),
        sa.Column("sales_invoice_id", sa.Uuid(), nullable=True),
        sa.Column("payment_date", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("method", sa.String(length=24), nullable=False),
        sa.Column("reference", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column(
            "tenant_id",
            sa.Uuid(),
            nullable=False,
            comment="Organization owning this record; enforced by foreign keys and reader RLS.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "method IN ('bank_transfer', 'cash', 'card', 'upi', 'cheque')",
            name=op.f("ck_payments_method"),
        ),
        sa.CheckConstraint(
            "(purchase_invoice_id IS NOT NULL) <> (sales_invoice_id IS NOT NULL)",
            name=op.f("ck_payments_exactly_one_invoice"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_payments_positive_amount")),
        sa.ForeignKeyConstraint(
            ["tenant_id", "purchase_invoice_id"],
            ["erp.purchase_invoices.tenant_id", "erp.purchase_invoices.id"],
            name=op.f("fk_payments_tenant_id_purchase_invoices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id", "sales_invoice_id"],
            ["erp.sales_invoices.tenant_id", "erp.sales_invoices.id"],
            name=op.f("fk_payments_tenant_id_sales_invoices"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["app.tenants.id"],
            name=op.f("fk_payments_tenant_id_tenants"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint("tenant_id", "id", name=op.f("uq_payments_tenant_id")),
        sa.UniqueConstraint("tenant_id", "payment_number", name="uq_payments_tenant_number"),
        schema="erp",
        comment="Invoice payments: purchases are outgoing; sales are incoming, in INR.",
    )
    op.create_index(
        "ix_payments_tenant_date",
        "payments",
        ["tenant_id", "payment_date"],
        unique=False,
        schema="erp",
    )
    op.create_index(
        "ix_payments_tenant_purchase_invoice",
        "payments",
        ["tenant_id", "purchase_invoice_id"],
        unique=False,
        schema="erp",
    )
    op.create_index(
        "ix_payments_tenant_sales_invoice",
        "payments",
        ["tenant_id", "sales_invoice_id"],
        unique=False,
        schema="erp",
    )
    # ### end Alembic commands ###
    _install_database_policy()


def downgrade() -> None:
    _remove_database_policy()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_payments_tenant_sales_invoice", table_name="payments", schema="erp")
    op.drop_index("ix_payments_tenant_purchase_invoice", table_name="payments", schema="erp")
    op.drop_index("ix_payments_tenant_date", table_name="payments", schema="erp")
    op.drop_table("payments", schema="erp")
    op.drop_table("stock", schema="erp")
    op.drop_index(
        "ix_sales_order_items_tenant_product", table_name="sales_order_items", schema="erp"
    )
    op.drop_index("ix_sales_order_items_tenant_order", table_name="sales_order_items", schema="erp")
    op.drop_table("sales_order_items", schema="erp")
    op.drop_index("ix_sales_invoices_tenant_order", table_name="sales_invoices", schema="erp")
    op.drop_index("ix_sales_invoices_tenant_due_status", table_name="sales_invoices", schema="erp")
    op.drop_index("ix_sales_invoices_tenant_date", table_name="sales_invoices", schema="erp")
    op.drop_table("sales_invoices", schema="erp")
    op.drop_index(
        "ix_purchase_order_items_tenant_product", table_name="purchase_order_items", schema="erp"
    )
    op.drop_index(
        "ix_purchase_order_items_tenant_order", table_name="purchase_order_items", schema="erp"
    )
    op.drop_table("purchase_order_items", schema="erp")
    op.drop_index("ix_purchase_invoices_tenant_order", table_name="purchase_invoices", schema="erp")
    op.drop_index(
        "ix_purchase_invoices_tenant_due_status", table_name="purchase_invoices", schema="erp"
    )
    op.drop_index("ix_purchase_invoices_tenant_date", table_name="purchase_invoices", schema="erp")
    op.drop_table("purchase_invoices", schema="erp")
    op.drop_index("ix_sales_orders_tenant_status", table_name="sales_orders", schema="erp")
    op.drop_index("ix_sales_orders_tenant_date", table_name="sales_orders", schema="erp")
    op.drop_index("ix_sales_orders_tenant_customer", table_name="sales_orders", schema="erp")
    op.drop_table("sales_orders", schema="erp")
    op.drop_index("ix_purchase_orders_tenant_supplier", table_name="purchase_orders", schema="erp")
    op.drop_index("ix_purchase_orders_tenant_status", table_name="purchase_orders", schema="erp")
    op.drop_index("ix_purchase_orders_tenant_date", table_name="purchase_orders", schema="erp")
    op.drop_table("purchase_orders", schema="erp")
    op.drop_index("ix_products_tenant_name", table_name="products", schema="erp")
    op.drop_index("ix_products_tenant_category", table_name="products", schema="erp")
    op.drop_table("products", schema="erp")
    op.drop_index("ix_suppliers_tenant_name", table_name="suppliers", schema="erp")
    op.drop_table("suppliers", schema="erp")
    op.drop_table("product_categories", schema="erp")
    op.drop_index("ix_customers_tenant_name", table_name="customers", schema="erp")
    op.drop_table("customers", schema="erp")
    op.drop_table("seed_runs", schema="app")
    op.drop_index(
        op.f("ix_analytics_principals_tenant_id"), table_name="analytics_principals", schema="app"
    )
    op.drop_table("analytics_principals", schema="app")
    op.drop_table("tenants", schema="app")
    # ### end Alembic commands ###
