"""Curated ERP schema context and question-based relation selection."""

from __future__ import annotations

import re
from dataclasses import dataclass

from app import models as registered_models


@dataclass(frozen=True)
class SchemaColumn:
    name: str
    data_type: str
    nullable: bool


@dataclass(frozen=True)
class SchemaTable:
    name: str
    description: str
    columns: tuple[SchemaColumn, ...]
    keywords: tuple[str, ...]


@dataclass(frozen=True)
class SchemaRelationship:
    source_table: str
    source_column: str
    target_table: str
    target_column: str


@dataclass(frozen=True)
class SchemaContext:
    tables: tuple[SchemaTable, ...]
    relationships: tuple[SchemaRelationship, ...]
    business_rules: tuple[str, ...]

    @property
    def table_names(self) -> frozenset[str]:
        return frozenset(table.name for table in self.tables)

    def column_names(self, table_name: str) -> frozenset[str]:
        for table in self.tables:
            if table.name == table_name:
                return frozenset(column.name for column in table.columns)
        return frozenset()

    def as_prompt_data(self) -> dict[str, object]:
        return {
            "schema": "erp",
            "tables": [
                {
                    "name": table.name,
                    "description": table.description,
                    "columns": [
                        {
                            "name": column.name,
                            "type": column.data_type,
                            "nullable": column.nullable,
                        }
                        for column in table.columns
                    ],
                }
                for table in self.tables
            ],
            "relationships": [relationship.__dict__ for relationship in self.relationships],
            "business_rules": list(self.business_rules),
        }


_TABLE_DETAILS: dict[str, tuple[str, tuple[str, ...]]] = {
    "customers": ("Customers who place sales orders.", ("customer", "client", "buyer")),
    "suppliers": ("Suppliers that fulfill purchase orders.", ("supplier", "vendor", "purchase")),
    "product_categories": (
        "Product categories used for inventory and sales grouping.",
        ("category", "categories"),
    ),
    "products": (
        "Product catalog with INR cost and selling prices.",
        ("product", "sku", "item", "catalog"),
    ),
    "purchase_orders": (
        "Purchase order headers from suppliers.",
        ("purchase", "procurement", "po", "supplier", "order"),
    ),
    "purchase_order_items": (
        "Line items on purchase orders.",
        ("purchase", "procurement", "line", "item"),
    ),
    "sales_orders": (
        "Sales order headers from customers.",
        ("sale", "sales", "revenue", "customer", "order"),
    ),
    "sales_order_items": (
        "Line items on sales orders.",
        ("sale", "sales", "revenue", "line", "item"),
    ),
    "purchase_invoices": (
        "Invoices received from suppliers.",
        ("purchase", "payable", "invoice", "supplier", "due"),
    ),
    "sales_invoices": (
        "Invoices issued to customers.",
        ("sale", "sales", "receivable", "invoice", "customer", "due"),
    ),
    "payments": (
        "Incoming and outgoing invoice payments.",
        ("payment", "paid", "collection", "cash", "upi"),
    ),
    "stock": (
        "Inventory snapshot by product and warehouse.",
        ("stock", "inventory", "warehouse", "reorder", "available"),
    ),
}

_BUSINESS_RULES = (
    "All monetary amounts are INR and use exact decimal values.",
    (
        "Sales order and sales invoice values are customer-facing; purchase values are "
        "supplier-facing."
    ),
    "Order totals equal subtotal plus tax_amount; item line totals are generated by PostgreSQL.",
    "Stock availability is quantity minus reserved_quantity.",
    "The database applies tenant row-level security; do not filter or infer tenant identifiers.",
)


class SchemaService:
    """Build a small, approved schema context instead of disclosing every relation."""

    def __init__(self, max_tables: int) -> None:
        self.max_tables = max_tables
        self._catalog = self._build_catalog()
        self._relationships = self._build_relationships()

    @staticmethod
    def _build_catalog() -> dict[str, SchemaTable]:
        catalog: dict[str, SchemaTable] = {}
        for table in registered_models.Base.metadata.tables.values():
            if table.schema != "erp" or table.name not in _TABLE_DETAILS:
                continue
            description, keywords = _TABLE_DETAILS[table.name]
            catalog[table.name] = SchemaTable(
                name=table.name,
                description=description,
                columns=tuple(
                    SchemaColumn(
                        name=column.name,
                        data_type=str(column.type),
                        nullable=column.nullable,
                    )
                    for column in table.columns
                    if column.name != "tenant_id"
                ),
                keywords=keywords,
            )
        return catalog

    @staticmethod
    def _build_relationships() -> tuple[SchemaRelationship, ...]:
        relationships: list[SchemaRelationship] = []
        for table in registered_models.Base.metadata.tables.values():
            if table.schema != "erp":
                continue
            for constraint in table.foreign_key_constraints:
                for element in constraint.elements:
                    target = element.column.table
                    if target.schema == "erp":
                        relationships.append(
                            SchemaRelationship(
                                source_table=table.name,
                                source_column=element.parent.name,
                                target_table=target.name,
                                target_column=element.column.name,
                            )
                        )
        return tuple(relationships)

    def context_for(self, question: str) -> SchemaContext:
        tokens = set(re.findall(r"[a-z0-9]+", question.lower()))
        ranked: list[tuple[int, str]] = []
        for table in self._catalog.values():
            search_terms = set(table.name.split("_")) | set(table.keywords)
            score = len(tokens & search_terms)
            ranked.append((score, table.name))
        ranked.sort(key=lambda item: (-item[0], item[1]))
        selected = [name for score, name in ranked if score > 0][: self.max_tables]
        if not selected:
            selected = ["sales_orders", "sales_order_items", "products", "customers"]

        # Include direct joins for the selected business relations when capacity permits.
        for relationship in self._relationships:
            if relationship.source_table in selected and relationship.target_table not in selected:
                selected.append(relationship.target_table)
            elif (
                relationship.target_table in selected and relationship.source_table not in selected
            ):
                selected.append(relationship.source_table)
            if len(selected) >= self.max_tables:
                break
        selected = selected[: self.max_tables]
        selected_set = set(selected)
        return SchemaContext(
            tables=tuple(self._catalog[name] for name in selected),
            relationships=tuple(
                relationship
                for relationship in self._relationships
                if relationship.source_table in selected_set
                and relationship.target_table in selected_set
            ),
            business_rules=_BUSINESS_RULES,
        )
